nbb:
  # 验证码类型 math 数字计算 char 字符验证
  captcha-type: math

server:
  port: 8090

spring:
  application:
    name: iot-console
  redis:
    host: localhost
    port: 6379
    database: 9
    password: root


logging:
  file:
    name: ${spring.application.name}
    path: d:\logs\

