nbb:
  # 验证码类型 math 数字计算 char 字符验证
  captcha-type: math

server:
  port: 8090

spring:
  application:
    name: iot-console
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nbb-iot?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 9
    password: root

  messages:
    basename: i18n/messages # 国际化资源文件路径


logging:
  file:
    name: ${spring.application.name}
    path: d:\logs\


mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
  # 搜索指定包别名
  type-aliases-package: io.github.nbb.iot.console.domain
  global-config:
    db-config:
      id-type: ASSIGN_ID


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # 登录用户持续30分钟没有操作系统，token就失效
  activity-timeout: 1800
  # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  is-read-cookie: false