server:
  port: 8070

spring:
  application:
    name: iot-gateway
  main:
    allow-circular-references: true

iot-gateway:
  client-id: iot-gateway-01

# 串口服务器列表
serial:
  server-list:
    - ip: 192.168.1.200
      port: 4196
#    - ip: 192.168.1.42
#      port: 8989


logging:
  file:
    name: ${spring.application.name}
    path: d:\logs\
